### ISSUE TITLE
Move log file path

### ISSUE THREAD

**Issue by tiffmay** [skyworksinc/skillbridge#5]
change the permissions to 775 on python_server.py in build.sh

This was the error I was receiving
![image](https://user-images.githubusercontent.com/50755819/128560858-f5b46f45-d24b-48ef-811a-a3f515a88fb8.png)

Permission for that file:
![image](https://user-images.githubusercontent.com/50755819/128561032-bd956c44-0112-49ce-b548-181ff4bdc140.png)

Permissions for that file that works (my dev-conda-channel):
![image](https://user-images.githubusercontent.com/50755819/128561422-d98a5b29-9b7b-40f8-9d14-685e7f6e748d.png)

**Comment by tiffmay** [comment]
Now that I'm thinking about this more, we might need to create this log file that has write permissions for all...

**Comment by curtisma** [comment]
hmm, seems that each user should have their own log in their project work area.  
It should be created each time it runs rather than once.

**Comment by tiffmay** [comment]
I guess we could change the LOG_FILE value and set it to their project work area. I'm not sure the best way to give it the path there. (one way would be though env vars)

https://github.com/skyworksinc/skillbridge/blob/d6f81f50dc45360059330148c0a872be3df35248/skillbridge/server/python_server.py#L12-L18 

We would also have to modify it here. 
https://github.com/skyworksinc/skillbridge/blob/d6f81f50dc45360059330148c0a872be3df35248/skillbridge/server/python_server.il#L8

It looks like there already is a log in their work_dir as well... This log file seems to be from ipcBeginProcess, while the one we are having issues with is skillbridge's logging file.

![image](https://user-images.githubusercontent.com/50755819/128570744-613e11b9-7ae1-46da-a035-4a49566f69a0.png)

https://github.com/skyworksinc/skillbridge/blob/d6f81f50dc45360059330148c0a872be3df35248/skillbridge/server/python_server.il#L192

**Comment by curtisma** [comment]
Let's name the Cadence IPC log as "skillbridge_skill.log" and
the python log as "skillbridge_python.log"
